# coding: utf-8

"""
    Payments

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class PaymentRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, amount=None, description=None, idempotency_key=None, payer_id=None, tax_rate=None):
        """
        PaymentRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'amount': 'float',
            'description': 'str',
            'idempotency_key': 'str',
            'payer_id': 'PaymentRequestPayerId',
            'tax_rate': 'float'
        }

        self.attribute_map = {
            'amount': 'amount',
            'description': 'description',
            'idempotency_key': 'idempotencyKey',
            'payer_id': 'payerId',
            'tax_rate': 'taxRate'
        }

        self._amount = amount
        self._description = description
        self._idempotency_key = idempotency_key
        self._payer_id = payer_id
        self._tax_rate = tax_rate

    @property
    def amount(self):
        """
        Gets the amount of this PaymentRequest.
        The gross amount in Swiss Francs (CHF). Includes the VAT. Negative value represents refund.

        :return: The amount of this PaymentRequest.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """
        Sets the amount of this PaymentRequest.
        The gross amount in Swiss Francs (CHF). Includes the VAT. Negative value represents refund.

        :param amount: The amount of this PaymentRequest.
        :type: float
        """

        self._amount = amount

    @property
    def description(self):
        """
        Gets the description of this PaymentRequest.
        The description or purpose of the payment to be shown on the bill. The description should be encoded in ISO-8859-1 charset, since those are guaranteed to be properly printed on the Swisscom bill.

        :return: The description of this PaymentRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this PaymentRequest.
        The description or purpose of the payment to be shown on the bill. The description should be encoded in ISO-8859-1 charset, since those are guaranteed to be properly printed on the Swisscom bill.

        :param description: The description of this PaymentRequest.
        :type: str
        """

        self._description = description

    @property
    def idempotency_key(self):
        """
        Gets the idempotency_key of this PaymentRequest.
        The key identifier provided by the API consumer used so that the same payment transaction cannot be made twice.For example, if a request to create a charge fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single charge is created.

        :return: The idempotency_key of this PaymentRequest.
        :rtype: str
        """
        return self._idempotency_key

    @idempotency_key.setter
    def idempotency_key(self, idempotency_key):
        """
        Sets the idempotency_key of this PaymentRequest.
        The key identifier provided by the API consumer used so that the same payment transaction cannot be made twice.For example, if a request to create a charge fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single charge is created.

        :param idempotency_key: The idempotency_key of this PaymentRequest.
        :type: str
        """

        self._idempotency_key = idempotency_key

    @property
    def payer_id(self):
        """
        Gets the payer_id of this PaymentRequest.


        :return: The payer_id of this PaymentRequest.
        :rtype: PaymentRequestPayerId
        """
        return self._payer_id

    @payer_id.setter
    def payer_id(self, payer_id):
        """
        Sets the payer_id of this PaymentRequest.


        :param payer_id: The payer_id of this PaymentRequest.
        :type: PaymentRequestPayerId
        """

        self._payer_id = payer_id

    @property
    def tax_rate(self):
        """
        Gets the tax_rate of this PaymentRequest.
        Tax rate (VAT) expressed in percent. Valid values 0.0, 2.5, 8.0. Default value is 0.0

        :return: The tax_rate of this PaymentRequest.
        :rtype: float
        """
        return self._tax_rate

    @tax_rate.setter
    def tax_rate(self, tax_rate):
        """
        Sets the tax_rate of this PaymentRequest.
        Tax rate (VAT) expressed in percent. Valid values 0.0, 2.5, 8.0. Default value is 0.0

        :param tax_rate: The tax_rate of this PaymentRequest.
        :type: float
        """

        self._tax_rate = tax_rate

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
